{
  description = "Caio's NixOS configuration";

  inputs = {
    # Nixpkgs
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
    # You can access packages and modules from different nixpkgs revs
    # at the same time. Here's an working example:
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    # Also see the 'unstable-packages' overlay at 'overlays/default.nix'.

    # Home manager
    home-manager.url = "github:nix-community/home-manager/release-26.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    # Hardware quirks
    nixos-hardware = {
      url = "github:NixOS/nixos-hardware/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # ACCELA + SLSsteam
    enter-the-wired = {
      url = "github:ciscosweater/enter-the-wired/d64bb7c3acfb74a65ebae2bba46ca565f17d4945";
      inputs.nixpkgs.follows = "nixpkgs-unstable";
    };

    # SLSsteam - Steamclient Modification for Linux
    sls-steam = {
      url = "github:AceSLS/SLSsteam/8fd895a222afaf500400cf2a07383b249ebd15e4";
      inputs.nixpkgs.follows = "nixpkgs-unstable";
    };

    # Pop Shell - keyboard-driven GNOME layer (master_noble branch)
    pop-shell = {
      url = "github:pop-os/shell/master_noble";
      flake = false;
    };
  };

  outputs = {
    self,
    nixpkgs,
    nixpkgs-unstable,
    home-manager,
    nixos-hardware,
    enter-the-wired,
    sls-steam,
    pop-shell,
    ...
  } @ inputs: let
    # Supported systems for your flake packages, shell, etc.
    systems = [
      "aarch64-linux"
      "i686-linux"
      "x86_64-linux"
      "aarch64-darwin"
      "x86_64-darwin"
    ];
    # This is a function that generates an attribute by calling a function you
    # pass to it, with each system as an argument
    forAllSystems = nixpkgs.lib.genAttrs systems;
  in {
    # Your custom packages
    # Accessible through 'nix build', 'nix shell', etc
    packages = forAllSystems (system: import ./pkgs nixpkgs.legacyPackages.${system});
    # Formatter for your nix files, available through 'nix fmt'
    # Other options beside 'alejandra' include 'nixpkgs-fmt'
    formatter = forAllSystems (system: nixpkgs.legacyPackages.${system}.alejandra);

    # Your custom packages and modifications, exported as overlays
    overlays = import ./overlays {inherit inputs;};
    # Reusable nixos modules you might want to export
    # These are usually stuff you would upstream into nixpkgs
    nixosModules = import ./modules/nixos;
    # Reusable home-manager modules you might want to export
    # These are usually stuff you would upstream into home-manager
    homeManagerModules = import ./modules/home-manager;

    # NixOS configuration entrypoint
    # Host-specific modules go in hosts/<hostname>/
    # Shared modules live in nixos/
    nixosConfigurations = {
      nixos = nixpkgs.lib.nixosSystem {
        specialArgs = {inherit inputs;};
        modules = [
          # Host-specific: hardware, GPU, peripherals (hosts/desktop/)
          ./hosts/desktop/hardware-configuration.nix
          ./hosts/desktop/gpu.nix
          ./hosts/desktop/default.nix

          # Hardware quirks
          nixos-hardware.nixosModules.common-cpu-amd
          nixos-hardware.nixosModules.common-gpu-nvidia

          # > Our main nixos configuration file <
          ./nixos/configuration.nix
        ];
      };

      # To add a new machine:
      #   1. mkdir hosts/<hostname>
      #   2. Copy hardware-configuration.nix from the target machine
      #      (generated by nixos-generate-config)
      #   3. Create hosts/<hostname>/default.nix for host-specific config
      #   4. Add a nixosConfiguration entry here:
      # laptop = nixpkgs.lib.nixosSystem {
      #   specialArgs = {inherit inputs;};
      #   modules = [
      #     ./hosts/laptop/hardware-configuration.nix
      #     ./hosts/laptop/default.nix
      #     nixos-hardware.nixosModules.common-cpu-intel
      #     ./nixos/configuration.nix
      #   ];
      # };
    };

    # Standalone home-manager configuration entrypoint
    # Available through 'home-manager --flake .#caio@nixos'
    # Uncomment to use home-manager standalone (dotfiles managed via stow):
    # homeConfigurations = {
    #   "caio@nixos" = home-manager.lib.homeManagerConfiguration {
    #     # Home-manager requires 'pkgs' instance
    #     pkgs = nixpkgs.legacyPackages.x86_64-linux;
    #     extraSpecialArgs = {inherit inputs;};
    #     modules = [
    #       # > Our main home-manager configuration file <
    #       ./home-manager/home.nix
    #     ];
    #   };
    # };
  };
}
